config/routes.rb
Rails.application.routes.draw do
  resources :flats
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :description, :address, :price_per_night, :number_of_guests, presence: true
  validates :price_per_night, :number_of_guests, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  def index
    if params[:query]
      @flats = Flat.where("name LIKE '%#{params[:query]}%'")
    else
      @flats = Flat.all
    end
  end
  # @flats = Flat.where("name LIKE '%garden%'"

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat, notice: 'Flat has been added'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Flat has been updated'
    else
      render :new
    end
  end

  def destroy
    @flat.destroy

    redirect_to flats_path, notice: 'Flat has been removed'
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f|%>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions btn btn-success">
    <%= f.button :submit %>
  </div>

app/views/flats/edit.html.erb
<%= simple_form_for(@flat) do |f|%>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions btn btn-success">
    <%= f.button :submit %>
  </div>
  <br>
  <td><%= link_to "See more", @flat, class: "btn btn-primary"%></td>
  <td><%= link_to 'Back', flats_path, class: "btn btn-primary"%></td>
<% end %>

app/views/flats/index.html.erb
<h1>Flats <%= @flats.count %></h1>
<form action="/flats">
  <input type="text" placeholder="Search" name="query">
  <input type="submit" value="Search">
</form>

<br>
<%= link_to 'Add Flat', new_flat_path, class: "btn btn-danger" %>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Guests</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @flats.each do |flat| %>
      <tr>
        <td><%= flat.name %></td>
        <td><%= flat.address %></td>
        <td><%= flat.number_of_guests %></td>
        <td><%= flat.price_per_night %></td>
        <td><%= link_to "See more", flat, class: "btn btn-primary"%></td>
        <td><%= link_to 'Edit', edit_flat_path(flat), class: "btn btn-success" %> </td>
        <td><%= link_to 'Delete', flat,
                        method: :delete,
                        data: { confirm: 'Do you want to delete it?'}, class: "btn btn-danger" %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/flats/new.html.erb
<%= simple_form_for(@flat) do |f|%>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
  </div>

  <div class="form-actions btn btn-success">
    <%= f.button :submit %>
  </div>
  <br>
  <%= link_to 'Back', flats_path %>
<% end %>

app/views/flats/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @flat.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @flat.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @flat.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @flat.price_per_night %><%="$" %>
</p>

<p>
  <strong>Number of guests:</strong>
  <%= @flat.number_of_guests %>
</p>
<td><%= link_to "Edit Flat", edit_flat_path, class: "btn btn-primary"%></td>
<td><%= link_to "Back to the list", flats_path, class: "btn btn-primary"%></td>
<td><%= link_to 'Delete', @flat,
                        method: :delete,
                        data: { confirm: 'Do you want to delete it?'}, class: "btn btn-danger" %> </td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>